[package]
name = "SeeVi-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-graphql = "5.0.8"
firebase = "0.9.1"
mongodb = "2.5.0"
tide = "0.16.0"
tokio = { version = "1.28.1", features = ["full"] }
