[package]
name = "graphql_query_maker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-graphql-parser = "^6.0.0"
regex = "^1.10.2"
serde_json = "^1.0.0"

[lib]
proc-macro = true
