name: Rust

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}'
    - name: Cache
      uses: actions/cache@v1.2.1
      with:
        # A directory to store and save the cache
        path: .cache
        # An explicit key for restoring and saving the cache
        key: cargo-artifact
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Start MongoDB in GitHub Actions
      uses: supercharge/mongodb-github-action@1.9.0
    - name: Run tests
      run: cargo test --verbose



